---
#- include_tasks: setup-RedHat.yml

- name: Check that the {{ openshift_temp_name }} exists
  stat:
    path: "/tmp/{{ openshift_temp_name }}"
  register: stat_result

- debug:
    msg: "file exists"
  when: {{ stat_result }}
  
- debug:
    msg: "file not exists exists"
  when: {{ !stat_result }}
  
  
- name: Download {{ openshift_temp_name }}
  get_url:
    url: "{{ openshift_url }}"
    dest: "/tmp/{{ openshift_temp_name }}"
    mode: 0440
  when: stat_result

- name: Extract openshift.tgz into destination
  unarchive:
    src: "/tmp/{{ openshift_temp_name }}"
    dest: "{{ openshift_root_path }}"
