---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
  mode: 0644

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker


- name: ensure needed directories are present
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/docker
    - /etc/systemd/system

- name: create directory for proxy file
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: docker_proxy

- name: create http-proxy.conf
  copy:
    content: |
      [Service]
      Environment="HTTP_PROXY={{ docker_http_proxy }}" "HTTPS_PROXY={{ docker_https_proxy }}" "NO_PROXY={{ docker_no_proxy }}"
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: restart docker
when: docker_proxy

- name: Allow access to insecure registry
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    regexp: ^ExecStart=
    line: ExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry {{ docker_registry_host }}
  become: yes
  
  
- name: Ensure Docker is started and enabled at boot. 
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
 
- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker
